### ISSUE TITLE
Question: How can i register if i receive this message: "we don't yet have support to send SMS to your carrier"

### ISSUE THREAD

**Issue by Henrijs112** [steemit/condenser#1200]
Hello, i did go to Facebook Steemit group and they did tell me go here, maybe someone [Dev.] can help me out:
**Step #1** add email >> Receive comfirmation email - Done
**Step #2** Confirm mobile phone [Problem] - Latvia, EU Country...
Receive message: "Unfortunately, we don't yet have support to send SMS to your carrier, please try again later."
Now have passed 2 weeks and nothing have changed... Please take a look at image.
**Image:** http://tinyurl.com/jcursap

Can someone help out? I really would like test out this network and help promote it further because i love what you guys have created.

Best Regards, 
Henrijs

**Comment by theghost1980** [comment]
Hi there. i am just a steemit user. Have you tried to re-check if you are typing correctly your mobile phone number?
have you tried again these days? (i mean it has been 25 days ago since you tried last time, maybe the issue could be fixed by now)
try again, just in case the platform fixed that already.

another idea I can give you, is if you have a friend in another country who can lend you his mobile phone number, maybe a very close friend or a family member who lives in another country as England or the US, maybe they can help you with another phone number.
I hope that helps!

**Comment by roadscape** [comment]
@Henrijs112 still having this problem?

**Comment by Henrijs112** [comment]
Wohoo i'm in... problem solved, now i can tell friends also...

**Comment by roadscape** [comment]
👍
