### ISSUE TITLE
Please enable embedding from https://www.steem.center/

### ISSUE THREAD

**Issue by Tadasu85** [steemit/condenser#1210]
![embed](https://cloud.githubusercontent.com/assets/7244892/23295451/c0c1bb50-fa3e-11e6-91fe-f941077d2185.png)

**Comment by thebitcoiner** [comment]
It seems there is a mistake in the parser where it thinks that URL is an actual image, most likely due to it ending in .png.

That URL is actually the link to a _page_ with images and not the image itself.

To get the URL of the image, on that page, it would be the links that give the resolution, or the Original file link, namely:

```
https://www.steem.center/images/thumb/1/1c/Reputation.png/800px-Reputation.png
https://www.steem.center/images/thumb/1/1c/Reputation.png/320px-Reputation.png
https://www.steem.center/images/1/1c/Reputation.png
```

Hope this helps.

**Comment by Tadasu85** [comment]
Oh thats actually a really good point thank you. and your alternative works thanks man.
