### ISSUE TITLE
Restore cashout feed

### ISSUE THREAD

**Issue by FreeBornAngel** [steemit/condenser#1331]
This feed let folks that don't query the blockchain directly to get a feel of the health of the platform.

Without this feature we will not be able to see who is not getting payouts.

If the answer is 'use the new links', payout and payout_comments, then those feeds need to not be random rather than chronological, imo.

**Comment by TimCliff** [comment]
@FreeBornAngel this is not the appropriate place to make enhancement suggestions. @sneak to close.

**Comment by TimCliff** [comment]
Can you please elaborate on what is broken? If possible, include a screenshot of the discrepancy?

**Comment by FreeBornAngel** [comment]
I gotta edit better,...

Here: 
https://steemit.com/payout
https://payout_comments

Do those appear to be chronological to you?

I'm assuming that their purpose was to track posts as they pay out.
Their being broken only disadvantages the non-technical among us, I guess.

**Comment by roadscape** [comment]
`payout` and `payout_comments` sort by the total pending payout, not time.

**Comment by FreeBornAngel** [comment]
So it is only the trending page as it pays out?

Ok, well I guess there isn't much point, they killed the old list for a reason.

Thanks for your time.

**Comment by roadscape** [comment]
Trending is based on creation time, except posts get boosted forward depending on how many rshares they've received. `cashout` was the only place you could see posts which were sorted by their payout date. It was removed because it was rarely used and thus cluttering the UI.

The `cashout` sort would be more appropriate for a block explorer as it's more of a power user feature.

**Comment by FreeBornAngel** [comment]
I must be rare, I used it quite often.
As a 'power user' I guess I'll just have to learn the code,....
