### ISSUE TITLE
Reblog custom_json operations have wrong id

### ISSUE THREAD

**Issue by Netherdrake** [steemit/condenser#1349]
Example output:
```
[28819,
 {'block': 11196859,
  'op': ['custom_json',
   {'id': 'follow',
    'json': '["reblog",{"account":"liondani","author":"furion","permlink":"suggest-a-name-1-000-steem-contest"}]',
    'required_auths': [],
    'required_posting_auths': ['liondani']}],
  'op_in_trx': 0,
  'timestamp': '2017-04-19T08:19:27',
  'trx_id': '7bfdddbd82c5eb1f628bc97de62909c1db759f4b',
  'trx_in_block': 2,
  'virtual_op': 0}]
```

The `id` should be `reblog`, not `follow`.

**Comment by roadscape** [comment]
`id` specifies the steemd plugin responsible for processing the json blob, and the `follow` plugin [handles](https://github.com/steemit/steem/blob/371280249bd9ae9d786fb8a7b8032d4968f75437/libraries/plugins/follow/follow_evaluators.cpp#L119) reblog commands. IMO it's fine since the functionality for `id=follow` is a small set anyway.

**Comment by Netherdrake** [comment]
I see. A little quirk I didn't know about.
