### ISSUE TITLE
A way to change voting power % instead of having to remove the vote then voting again.

### ISSUE THREAD

**Issue by Transisto** [steemit/condenser#1448]
It's taking extra steps and It seems like it could save a transaction in the blockchain.

**Comment by TimCliff** [comment]
@Transisto - this is a really good suggestion, but it isn't really a variance. For enhancement suggestions can you follow the process described in the GitHub guidelines for the repository? (Create a Steemit post, and email Sneak if it has widespread support)

If you are going to work on the pull request yourself, then the issue is fine, but it would be good to mention in the text that you will be working on it.

**Comment by roadscape** [comment]
IMV, this case is pretty rare, and this logic would increase complexity (e.g. extra "losing curation rewards message" needs to pop up when confirming a 0% vote when there is an existing vote)
