### ISSUE TITLE
Need to show rules for posting: per-day limits, max edit time, & misc clarifications

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#153]
There are rules which are not clear to new posters who have not read the whitepaper and kept up with changes. 

We need a simple dialog accessible from a "Posting Help" link on the Submit Post page with the following items:
- Decreased rewards for more than 4 top-level posts per day
- A post can only be edited during the first payout (to be extended in next hf)
- ??

(this is just a start, submit any other important guidelines & rules of note here)

**Comment by aaroncox** [comment]
Brainstorming here based off what I've heard, some of this might be too much for a simple posting help page. It all depends on how deep we want it to go through.

- The first image you use in the post is the thumbnail.
- An explanation of how to choose proper tags. 
- Possibly out of scope of this "Posting Help", but explanations on rewards (or maybe a link to this?):
  - Still a lot of people confused about the 75%/25% split, 
  - Why the value goes up and down over time. 
  - Payouts at 24hr / 30day.

**Comment by mcifani** [comment]
A few thoughts:  

- A thumbnail preview when creating your post.  Added user benefit with cropping displayed(later on a full cropping tool).  Also this could help not having to explain the first image/to thumbnail since it will be more obvious. 
- Next to Potential Payout a "Learn More" directs to the posting help guide
- Posting help guide could be very visual and wizard like (good for brand new inexperienced users)

**Comment by roadscape** [comment]
- Posts can only be promoted during first payout

**Comment by roadscape** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Posting Help Guide #153](https://trello.com/c/sj9OVmgG/102-posting-help-guide-153)

**Comment by TimCliff** [comment]
It seems that the original need for the issue is no longer there. Some of the items no longer apply. Most the other items are handled in the FAQ. I will add info about the thumbnail image, as well as the current edit restrictions in my next FAQ edit. This can probably be closed unless there are plans to add something more than what is there.

**Comment by roadscape** [comment]
I concur that the FAQ covers most of these points. Thank you.
