### ISSUE TITLE
Info pop-up doesn´t stick to name when scrolling

### ISSUE THREAD

**Issue by JohannesKnecht** [steemit/condenser#1533]
At least in my opinion I would stick that to the Name or let it disappear if a user starts scrolling.

![2017-06-27 12](https://user-images.githubusercontent.com/27769517/27598517-0e980112-5b66-11e7-8191-910215ae52f5.png)

![2017-06-27 11](https://user-images.githubusercontent.com/27769517/27598516-0e87dfda-5b66-11e7-8a5f-6e27d8f4dc11.png)

**Comment by gl2748** [comment]
This is being caused by a bug in the [`react-foundation-components`](https://github.com/aruberto/react-foundation-components) module that is being used:
There's this typo - note `constainer` !== `container`:
https://github.com/aruberto/react-foundation-components/blob/master/src/util/overlay-trigger/index.js#L321
As well as the fact that the `<LinkWithDropdown/>` component from that module does not take a target container as a prop, so that when it calls:
https://github.com/aruberto/react-foundation-components/blob/master/src/util/overlay-trigger/index.js#L164
It defaults to the `body` element. The overlay is therefore given the static behavior relative to the scrolling `FullPost` element. Relative to the `body` element it's behaving as designed. 

I propose using the [`react-overlays`](https://github.com/react-bootstrap/react-overlays
 https://github.com/react-bootstrap/react-overlays) module to replace `react-foundation-components` overlay functionality across the site - in fact the latter just seems to be a buggy implementation of the former...

Towards this goal I've swapped out the dependency in Steem's `Author` component to demonstrate how this might work...  PR to follow.

**Comment by gl2748** [comment]
PR here:
https://github.com/steemit/condenser/pull/1548

**Comment by plink01001** [comment]
Is this still an issue, or can it be closed?
