### ISSUE TITLE
Recovery Fail because I do not know the RECENT PASSWORD - Help out my friend - Bantu teman saya @syifaola

### ISSUE THREAD

**Issue by dejoel** [steemit/condenser#1604]
https://mail.google.com/mail/u/0/?ui=2&ik=5d4141593e&view=fimg&th=15da3bc2a29ba9b0&attid=0.1&disp=emb&realattid=ii_15da3bb86552a507&attbid=ANGjdJ9r2FWxxgIPT2Dx17CSkOPpI62Ar6eiNC-Fl2vLsUQ3GbAJGvRPhR0To0JEgxcgeoIQRlCz0RUXUD1TYV7nXu9N2FnR5T-XIwdxk_FlzOkyhyJ-NzVKtiILfcw&sz=w928-h522&ats=1501693009167&rm=15da3bc2a29ba9b0&zw&atsh=1

Please check the link

**Comment by TimCliff** [comment]
The stolen account recovery process does not allow you to recover an account if the password was lost or forgotten. It only allows you to recover an account if someone has changed the password in the last 30 days, and you still have the previous password that was used / working before the change.

**Comment by dejoel** [comment]
I have received confirmation of account recovery but I do not know RECENT PASSWORD because I only have the first password in steemit .. |
Or more clearly you can see the following link 
http://i.imgur.com/up9TM0v.png

**Comment by jredbeard** [comment]
The 'recent password' would have been the same one used to initiate the recovery process, which was approved on May 14th (probably the original password). Since the password was changed April 24th, the 30 days to initiate and finish the recovery process is long passed. This is hard rule of the blockchain and is not up to us.
