### ISSUE TITLE
IDEA: Multi-language content creating

### ISSUE THREAD

**Issue by Traderdude93** [steemit/condenser#1608]
I'm Dutch and will be staying in South-Korea for a while for my studies. For the homefront I'll be writing blogs regularly on Steemit to stay in touch and sort of as a journal. However, I also have English-speakers in my network who would like to keep track. 

My idea is as follows: A multi-layered blog in which you can select the preferred language the content creator has made. For example, I will write my content in Dutch and in English. So any viewer can select the language of preference to read the content! It would be an option to choose, like a small countryflag on the topright! 

I would really love this function as it makes it much easier and not making me feel like a spammer whenever I post things twice... 

Kind regards,

TD93

**Comment by TimCliff** [comment]
It is a good suggestion. I linked to it in the main issue that is tracking the "language handling discussion". For future reference though, it is best to make these types of suggestions as Steemit posts, and use appropriate tags so they get attention, rather than opening a GitHub issue for them.

@sneak to close.

**Comment by Traderdude93** [comment]
Will do, thanks!

**Comment by sneak** [comment]
We are going to be vastly improving the language support in condenser soon; supporting authors that write in multiple languages is probably low-priority though.  Your best bet for the near term is using separate accounts for your posts in each language.
