### ISSUE TITLE
Unable to update profile page.

### ISSUE THREAD

**Issue by martintiller** [steemit/condenser#1661]
Hi, I'm unable to update my profile page.  Whenever I type in a change the update button does not highlight allowing me to change my settings.

Here is what it looks like before I changing anything 
![steem profile issue 1](https://user-images.githubusercontent.com/31048168/29334507-9ae83188-81d5-11e7-9ab4-77cc2e0c9f90.png)
Here's what it looks like when I change something.

![steem profile issue 2](https://user-images.githubusercontent.com/31048168/29334546-b9616a58-81d5-11e7-96dc-00fb38f255ea.png)

I am using Google Chrome.  I also noticed this is an issue on my Kindle tablet as well, the same issue of not being able to update.

**Comment by roadscape** [comment]
I believe the issue here is that 'website' is not in the proper format (it needs to start with `http://` or `https://`). Please try that; if the error persists leave a comment here.

**Comment by sneak** [comment]
@roadscape this is a UX failing of condenser if true.

**Comment by roadscape** [comment]
@sneak I've seen this error once or twice before, most likely it's due to originally more lax rules when profile data was introduced. And in this case, I believe just touching the field is enough to get visual indicator of the error (e.g. if user tabs through the form, the issue will be obvious).

**Comment by martintiller** [comment]
The website is https.

And when I over the update button I get the red circle with a line through it.

![2017-08-16 2](https://user-images.githubusercontent.com/31048168/29363688-f1845808-825e-11e7-8f19-fabbbf8c35d6.png)

And the screenshot does not record the cursor when I hover over it.

**Comment by roadscape** [comment]
Where it says `martintiller.com` try changing it to say `https://martintiller.com`

**Comment by martintiller** [comment]
Holy Cow!  That worked.  Never would have guessed that in a million years.  Sorry for not understanding that at first.

**Comment by sneak** [comment]
@roadscape still a bug - and i guess i'm not being clear: *it's not an error*. requiring a fully formatted URI from a user is ridiculous as this thread clearly illustrates.  the form should be a lot smarter, and detect something that looks like a domain name and prepend `https://`.

**Comment by rayadav** [comment]
I agree with @sneak. I don't think it's reasonable to expect a user to prepend the protocol to the domain name.

Also, automatically prepending `https://` to the domain name entered by the user might not be a good idea. If the domain name entered by the user is only accessible over `http`(because they didn't have a cert for https or didn't know how to enable it or any other reason), prepending `https://` will make whoever clicks the link access the website on port 443 which will return a protocol error. On the other hand, if someone does have a domain accessible over `https`, if we try to access it over `http`, the server *almost always* redirects the request to port 443.

So I think the best approach will be to just let the user enter their domain name and store it as is. When the website link is clicked, this will default to accessing the domain over `http` and if `https` is set up then the request will be redirected by the server.

**Comment by sneak** [comment]
No. It is 2017. If your site does not support HTTPS it is not functioning correctly. If we prepend any default, it will be https://

**Comment by sneak** [comment]
Also, relying on an http-to-https redirect assumes a nonmalicious network, as the redirect is served over an unauthenticated connection. That's the whole point of TLS.

**Comment by rayadav** [comment]
> No. It is 2017. If your site does not support HTTPS it is not functioning correctly.
You know, that would be a much better error message than the standard "Invalid URL" message.
![screen shot 2017-08-19 at 19 33 23](https://user-images.githubusercontent.com/7298668/29490803-57630512-8515-11e7-8e07-fee2cb0dd43c.png)

I don't think it will be a good idea to prepend a default to a domain name without the user's knowledge because it might render the link inaccessible.
The question here is that of usability vs security and finding a balance. If an attacker wants the user to access a malicious url, they can also put it in the blog post body or anywhere that a url is allowed. So unless the intention is to prepend `https://` to everything, it doesn't make sense to do it here either.

> Also, relying on an http-to-https redirect assumes a nonmalicious network, as the redirect is served over an unauthenticated connection.
Http-to-https redirects is a thing. Try accessing `http://steemit.com` or `http://github.com` and you'll see a 307 in the network trace. I haven't found an often-visited website not doing redirects. The choice becomes very simple when you have two options - just deny a request over `http://` and make the visitor think your website is down or redirect it to `https://`?

**Comment by Gandalf-the-Grey** [comment]
FYI:
2017, that's exactly why you are seeing 307 instead 301 out there.
Both steemit.com and github.com would result in 307 because of HSTS when using modern browsers.
Chrome would show you such internal redirect without even making a request to the network because it already knows (preload) that steemit is not going to talk without transport security.
Only obsolete systems reach port 80 to get 301 redirect ( putting it at risk as mentioned by @sneak )

**Comment by sneak** [comment]
If your website doesn't work over TLS, it might as well be down.

**Comment by plink01001** [comment]
Are there plans to make any changes for this issue, or should it be closed?

**Comment by bnchdrff** [comment]
we can fix this issue by doing one or both of these two things:

* validate each form field on page load -- not just after the field has been modified. this will catch any errors related to values that had been set prior to the validation being put in place

* after a value has been entered into the website field, test it with regex `^https?:\/\/` and if it does not match, prepend `https://`

to do either of these things we need to make some changes to the homespun react form library this component is currently using.

**Comment by bnisevic** [comment]
This is very confusing issue. I experienced it my self too.

**Comment by roadscape** [comment]
Functionality moved to wallet, should be rare. Closing; if it persists please file at https://github.com/steemit/wallet/issues
