### ISSUE TITLE
Remove inactive witnesses from the voting page

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/condenser#1783]
Users often vote for disabled witnesses in the Top 50. I suggest you list only the active witnesses.
https://steemit.com/~witnesses

**Comment by TimCliff** [comment]
@Jolly-Pirate as per the repository's <a href="https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md">guidelines for contributing</a>, issues should not be opened for enhancement suggestions unless you are planning to submit a pull request. If you are, you should indicate that the issue is to track the item you are developing and get input. If you are not planning to develop it, then the issue should be closed.

Regarding the change proposal itself, I do not think it is a good idea. While it solves one problem, it creates others. Many times witnesses will temporarily suspend their witness node, but resume shortly after. Hiding these witnesses would not be an accurate representation of the current voting. Also, it would make it more difficult for users who are voting on disabled witnesses to see who they are voting for and remove their votes. It can also be argued that knowing there are inactive witnesses with more votes than active ones is useful information that stakeholders and other witnesses may still want to see.

**Comment by Jolly-Pirate** [comment]
Very well then, I'll close it. I hope Steemit would think about this suggestion though.
