### ISSUE TITLE
0.01 post/comment potential payout rounding error

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1819]
Based on discussions with people who are familiar with the steemd logic, steemd will not pay out post/comment rewards when the potential payout is 0.01. It only starts to pay out at 0.02. This can lead to poor user experience (especially for brand new users) when their first experience with the payout process is a 0.01 post or comment that doesn't get paid after the 7 days. Even though it is only a very small amount of money, for new users this may lead to a bad impression of the site overall, because it feels like it is either broken or cheating them. To better improve the UX, 0.01 pending payments should be shown as 0.00.

**Comment by azman17** [comment]
this seems to be causing a bad impression on the whole site and new users,
dikarnakan, for novice users very difficult to get potential 0.01 ..

but, for steemit advancement, it would be good to run in accordance with the discussions that have been carried out

**Comment by quochuy** [comment]
https://github.com/steemit/condenser/pull/3335

**Comment by economicstudio** [comment]
not sure this is a good idea, since this may induce another UX problem. For instance, many UIs show vote value. Say it shows 0.01, but after voting, pending payout (given that it was the first, which can happen quite likely for comments) can be shown as 0.00.

I think this behavior may just need to be well-documented in FAQ or so.

**Comment by quochuy** [comment]
@economicstudio hmmm at the same time vote value and pending payout are different things, the vote value might well be 0.01 but that will result in 0.00 payout. The change here is to show an accurate estimate of what the payout will be.

We can still do both, show 0.00 as payout and update the FAQ explaining why the vote value is 0.01 but the payout is 0.00

**Comment by economicstudio** [comment]
Hi @quochuy thank you for your comment. I understand the purpose and I agree that it has pros. But for instance, these days $0.02 needs 1000 SP. Normally that problem only occurs to comments not posts. Until a user reaches 1000 SP, their vote will always be shown as $0.00 (as opposed to what busy/steempeak says) on comments. I'm worried about this bad UX. How long does it take to get 1K sp without buying steem. quite long.

So rather than changing the current behaviour, updating FAQ might be better, since FAQ should be updated anyway. Of course, it's just my opinion. thanks.
