### ISSUE TITLE
Open Post as main view from post list

### ISSUE THREAD

**Issue by relativityboy** [steemit/condenser#1917]
**When opening a post from a post list view, should open as new page & preserve history**

Opening a post in a modal by default is a bad user experience. Clicking on a post link should result in a 'post page' view for a better user experience.

If possible, clicking on the back button will reload the previous' page & page state (the users place in the post list would be preserved)

**Comment by pkattera** [comment]
@relativityboy I agree – I'm all for this change!

**Comment by bnchdrff** [comment]
an additional expectation that should be met if we use react-router to link to posts instead of using the overlays:

expected behavior:

When I go to the homepage, click on a post, and click on my browser's "back" button and return to the homepage, and then click on my browser's "forward" button, I expect to return to the post I'd just been reading.

acutal behavior: forward history is lost, and the forward button isn't clickable.

**Comment by relativityboy** [comment]
@bnchdrff - 
'actual behavior' sounds like you're reporting a bug. Do you mean "current modal-type behavior doesn't put anything in history" ?

**Comment by bnchdrff** [comment]
yes, it's a bug as you just described, and it would hopefully get fixed by not using a modal

**Comment by plink01001** [comment]
Has this been addressed / can this be closed?

**Comment by bnchdrff** [comment]
a partial fix was deployed in #1919 but clicking on a post's image still opens a modal

**Comment by relativityboy** [comment]
@bnchdrff - thanks. That image thing is a bug. Thought I got all the <a> tags.
