### ISSUE TITLE
figure out why #2113 passed tests but wasn't deployable, fix tests to fail in this case

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#2167]
For some reason #2113 passed tests but wasn't deployable.  Make sure that whatever caused it to be undeployable also causes it to fail tests/fail build.

**Comment by goldibex** [comment]
The packages `medium-editor-insert-plugin` (which was the subject of #2113) and `blueimp-file-upload` are both direct dependencies of condenser as specified [here](https://github.com/steemit/condenser/tree/master/webpack/base.config.js#L64). This has been the case since the initial commit of the repository (06c90aa).

`medium-editor-insert-plugin` and `blueimp-file-upload` as packages are both referred to by  `webpack/base.config.js` using `require.resolve`. This effectively conceals them from any normal static analysis tool.

On 7 December 2016, in commit ad8ffb7, @jcalfee removed the dependency `blueimp-file-upload` from `package.json` without removing the corresponding `require.resolve` from `webpack/base.config.js`. This left condenser in an invalid state; starting from ad8ffb7, the package `blueimp-file-upload` only existed as a transitive dependency of `medium-editor-insert-plugin`.

On 28 October, in commit 6c137dd, @roadscape merged PR #551, previously approved by @jcalfee, which claimed to remove the usage of `medium-editor-insert-plugin` from the codebase. This PR was erroneous in that it neither removed `medium-editor-insert-plugin` nor `blueimp-file-upload` from `package.json`, nor did it remove the `require.resolve` entries from `webpack/base.config.js`.

From 6c137dd onward, both `medium-editor-insert-plugin` and `blueimp-file-upload` were hanging dependencies. They were not referred to by any code inside condenser, but their presence was requested in an inconsistent and irregular way by `base/webpack.config.js`.

@jnordberg noticed that `medium-editor-insert-plugin` was not referred to as an import anywhere in the codebase and opened #2113 to remove it. He should have examined the entire repository, not just the `src` directory, for references to the file. If he had he would have discovered the hanging references in `base/webpack.config.js`.

Our automated test suite continued to pass after #2113 was merged because the unit tests as currently configured do not rely on Webpack. This is not unusual for a React/ES6 application, as Webpack is exceptionally slow and in some instances takes more than a minute to finish a build.

I therefore submit the following proposals for additional followup work, in order of priority:
- [ ] Remove the references to `medium-editor-insert-plugin` and `blueimp-file-upload` from `webpack/base.config.js`.
- [ ] Remove `medium-editor-insert-plugin` from `package.json`, reinstating the change proposed in #2113.
- [ ] Reduce our Webpack configuration to a small shim that does not (and cannot) do anything the module loader for the test suite cannot. There may be implications here for code splitting and dynamic loading (which we do to reduce condenser's considerable throw weight).
- [ ] Add functional tests (via Selenium or some React-friendly tool) that run the application in production mode and perform a few basic tasks like signing in and reading posts.

**Comment by goldibex** [comment]
cc @sneak @relativityboy

**Comment by sneak** [comment]
lgtm!

**Comment by gl2748** [comment]
regarding:
> Reduce our Webpack configuration to a small shim that does not (and cannot) do anything the module loader for the test suite cannot. There may be implications here for code splitting and dynamic loading (which we do to reduce condenser's considerable throw weight).

related:
https://github.com/steemit/condenser/issues/2115

**Comment by bnchdrff** [comment]
estimate: 2 SP

**Comment by bnchdrff** [comment]
also ensure the `webpack` step in docker emits errors properly so that if the build isn't successful, docker notices
