### ISSUE TITLE
Make transfers from the "bad actors" list appear differently in the UI

### ISSUE THREAD

**Issue by dnotestein** [steemit/condenser#2206]
Motivation: bad actors can perform phishing attempts by sending transfer messages that appear to come from legit steem service partners such as exchanges. 

Maybe grey these transfer memos with a warning when you hover over them.

**Comment by gl2748** [comment]
@dnotestein can you provide a screenshot of what one of these currently look like?

**Comment by gl2748** [comment]
Specifically, for people on bad actors list.

**Comment by gl2748** [comment]
Later we can look up low-reputation.

**Comment by bnchdrff** [comment]
@pkattera will mock something up quick

**Comment by sneak** [comment]
The rough idea: nsfw-style clickwall over memo field.

**Comment by bnchdrff** [comment]
transfer history with one memo in normal style & two from bad actors, not revealed yet:

![screenshot from 2018-02-07 15-29-05](https://user-images.githubusercontent.com/99194/35940040-e99fa358-0c1b-11e8-9b13-4fa034e1ee02.png)

after clicking on the first reveal link:

![screenshot from 2018-02-07 15-29-44](https://user-images.githubusercontent.com/99194/35940049-ed3c199c-0c1b-11e8-9bc4-c12084fc0f5d.png)

title on the reveal link is "This memo is related to a transaction sent by a known bad actor, and may contain misleading information."

**Comment by roadscape** [comment]
Would it be better for the label read "Caution" or something else instead of "Bad actor"? I.e. treat these as "suspected" bad actors. IMO `BAD ACTOR` all up in the wallet UI looks scary for normal people.

**Comment by pkattera** [comment]
I like @roadscape's suggestion of using the label 'caution'. How about this text:

<img width="732" alt="screen shot 2018-02-07 at 1 01 37 pm" src="https://user-images.githubusercontent.com/1121139/35941441-140b352c-0c07-11e8-9c2b-f22e126207c2.png">

**Comment by sneak** [comment]
The “Reveal memo.” part is only known to be a verb/action if you know about our clickwall tradition.  It’s entirely unclear to a new user that it’s a clickable action.  This is not a good UI for a clickwall.

**Comment by sneak** [comment]
I think perhaps a scratch-off model like Geckoboard uses for their API keys is preferable.  Regardless, I’d like to see a good design here before implementation begins.

**Comment by sneak** [comment]
This represents an ordering failure - #2485 should not have started until we had a good design for the feature.

**Comment by pkattera** [comment]
@sneak Can you please suggest a better label name than: 'Reveal memo'

**Comment by pkattera** [comment]
I've removed the outline from the 'Caution' label. Sidenote: we'll need to see how this should be applied for the NSFW label which currently uses the outline pattern.

For the CTA, I've chosen to use an underline instead of a button, since adding the outline for the button  makes it too visually prominent. Due to the CTA also containing quite a lot of text (in order to be explicit), positioning it to the right hand side is not going to be elegant (especially on mobile).

<img width="734" alt="screen shot 2018-02-07 at 1 48 13 pm" src="https://user-images.githubusercontent.com/1121139/35943365-92f25afe-0c0d-11e8-9a5d-cc52aef5654a.png">

Text:  

CAUTION

This is from an account that looks fraudulent. If you wish, you may temporarily reveal this content which may contain dangerous links.

Reveal potentially unsafe memo

**Comment by bnchdrff** [comment]
@sneak can you provide feedback on pon's idea shown above?

**Comment by sneak** [comment]
I still don't like that the link text is an imperative instruction "Reveal ..." to the user telling them to do the thing we are trying to encourage them not to do.  It's better than it was, though.  If were up to me I'd veto it, but it's Pon's show. :)

**Comment by bnchdrff** [comment]
"I understand the risk; show anyway."
