### ISSUE TITLE
"Steem bandwidth limit exceeded" when I didn't even finish making my account?

### ISSUE THREAD

**Issue by DonnieBae** [steemit/condenser#2315]
I heard bandwidth issue is solved when you deposit small amounts of STEEM coin to your account.
But what happens if you are finishing up making your account (getting the long password) and you click "Create Account"  and get the error....??

4100000 plugin_exception: plugin exception Account: steem bandwidth limit exceeded. Please wait to transact or power up STEEM. {"account":"steem","account_vshares":"939236279575","account_average_bandwidth":"8886894394994","max_virtual_bandwidth":"3618273912422400000","total_vesting_shares":"405615648593053634"} th_a witness_plugin.cpp:409 update_account_bandwidth {"trx":{"ref_block_num":56203,"ref_block_prefix":3082200487,"expiration":"2018-01-10T15:03:48","operations":[["account_create_with_delegation",{"fee":"0.500 STEEM","delegation":"57000.000000

**Comment by stmoreau** [comment]
Also experiencing this!

Hoping that when it gets resolved we'll be able to create our account and not get blocked due to some weird loophole.

Thanks for raising it @DonnieBae 👍

**Comment by snow961** [comment]
hello @stmoreau  How to solve this problem?

**Comment by etuckeriv** [comment]
Also having this issue trying to login to steemit for the first time

**Comment by josclementes** [comment]
I have the same problem the link came to me 3 goras ago

**Comment by stmoreau** [comment]
I believe that this issue is making a lot of people rejecting steemit as a platform and since there is not much I can do with my knowledge, I will tag the top 10 contributors of this project to bring this issue to their attention.

Hoping they won't be too annoyed with this.
@roadscape 
@valzav 
@pkattera 
@relativityboy 
@svk31 
@bnchdrff 
@originated 
@TimCliff 
@jnordberg 
@sneak

**Comment by oalsing** [comment]
Same!

**Comment by sneak** [comment]
To those in this thread - this is a temporary condition due to the huge number of signups we're processing at the moment.  It will be resolved soon.  The "bandwidth" being referred to is not that of your new account, but that of the account that we use to create accounts - it's creating so many we need to provide it with more Steem Power.  Stay tuned!

**Comment by DonnieBae** [comment]
@sneak thank you for the information!

**Comment by krischik** [comment]
Google search directs to this closes ticket  #2268 which has quite a few more users which can't finish creating there account.

@AngelicaPerduta

**Comment by oalsing** [comment]
Problem resolved on my side! https://steemit.com/@oscaralsing/

Thanks to all developers working to fix this <3

**Comment by josclementes** [comment]
ready, I could finish my registration

**Comment by etuckeriv** [comment]
Woot woot! Me too! https://steemit.com/@eddietheorange
