### ISSUE TITLE
Change 'Password' to 'Master Private Key'

### ISSUE THREAD

**Issue by realnedscott** [steemit/condenser#2329]
In all areas where "password" is used.

**Comment by pkattera** [comment]
@nedsteem What's your rationale behind this change?

**Comment by nedsteem** [comment]
The connotation of password:  ‘user can create their own’ ‘user can have password recovered via website’ — because of these connotations we should strive toward something that can take on new meaning (of singular responsibility) — Master Private Key shares connotation with standard cryptographic private keys, while also conveying a hierarchy of keys — it may be fitting, or there may be a better term

**Comment by TimCliff** [comment]
Do we want to go into the subtleties of the different keys? For example, generally it is best to recommend that users only login with their posting key when they are posting, voting, etc. Even when they are doing token transfers, it is best to recommend that they use their active key instead of their master key. Ideally (if users are following proper security measures) they should really only be using their master key if they need to change their keys or recover their account.

**Comment by Jolly-Pirate** [comment]
The password is not a *private key*. The private keys are derived from it.
