### ISSUE TITLE
Add i18n support

### ISSUE THREAD

**Issue by f3rnando** [steemit/condenser#233]
I'm creating this issue in order to begin discussions on i18n support for steemit.com given that Im working into a clean, updated fork of this repo to include this feature.

Core points, questions and insights:
1. Adding i18n support is quite easy, the biggest efforts reside on translation and on keeping translation files updated.
2. I will PR as soon as spanish translations are done, in order to make merging relevant and useful right away.
3. The modules/plugins that I chose are: [react-intl](https://github.com/yahoo/react-intl) and [babel-plugin-react-intl](https://github.com/yahoo/babel-plugin-react-intl). Are these fine? if any other should be considered, please propose it ASAP.
4. The current i18n branch can be found here: [f3rnando/steemit.com/tree/i18n](https://github.com/f3rnando/steemit.com/tree/i18n) 
5. The current status compare of steemit.com:master > f3rnando:i18n [here](https://github.com/steemit/steemit.com/compare/master...f3rnando:i18n?expand=1)
6. Language selection should be automatic based on user locale
7. A chinese speaking user might access from a browser asking en-US, and he might want to override that language selection. I will not develop this UI feature, I believe it is subjective and the steemit team will take over this task.
8. I may give access to this repo to whoever wishes to collaborate and/or audit it.

Please reply referring to the list number, if any.

Updates coming soon.

**Comment by f3rnando** [comment]
If this proposal is given green light, I will rename the branch to reflect this issue's number.

**Comment by mynameiskeo** [comment]
Nice initiative... Was trying to work on this for a while, and bring developers to it. Heimindanger started something with me on http://94.23.30.172:3002/  (FR), and i'm finally quite BUSY on another project :) 
Very glad you work on it

https://github.com/yahoo/react-intl looks Ok
you can also have a look to https://www.npmjs.com/package/i18n-react

**Comment by skzap** [comment]
Hi @f3rnando, we want to make a French website for steem with @mynameiskeo 
I would be able to help you for porting the code.

1. Agreed, there will be a lot of edits but it should be pretty straightforward.
6. We could also store the language preference of a user in the json_metadata, but I agree by default use the locale.
7. Different language clones actually serve a bigger purpose than just translating. They also promote certain tags (#ru , #cn , etc). If we have a UI to change language directly inside steemit.com I'm afraid these communities might die.
8. Please do, also can I contact you on steemit.chat? I am @heimindanger there

**Comment by mynameiskeo** [comment]
About language preference, we worked on Steemscript, which is a JSON standard for this json_metadata from user account. It will be released very soon 

will look like this
`{
    "version": "0.0.1",
    "dns": {"records":[["@","CNAME","steem.io"]]}},
    "profile": {
        "name": "Ned Scott",
        "email": "ned@steem.io",
        "birthday": "12/12/1212",
        "gender": "male",
        "about": "CEO and Co-founder at Steemit",
        "first_name": "Ned",
        "last_name": "Scott",
        "location": "New York",
        "timezone": "-5",
        "locale": "en_US",
        "language": ["en"],
        "website": "",
        "cover_image": "",
        "profile_image": ",
        "featured_post": ""
    }`

I also had the idea to show somehow the local currency equivalence, ($, €, CNY, JPY, etc)

handle TimeAgo, Date format, and promoted language tags

Please contact heimindanger and me @ekitcho @heimindanger so we can discuss about it

**Comment by valzav** [comment]
@mynameiskeo I think we can adopt format like this. 
Btw why do you need dns record?
Also as far as I know there is one guy who is already working on i18n, let's see how he has advanced with his implementation, if he is ahead of anybody else we can take his solution as a base one.

**Comment by mynameiskeo** [comment]
@valzav about the format, we did spend time to discuss with several developers who planned or did use this json_metadata and try to find out the requirement.

If you know the guy let us know so we can figure out how to contribute. We definitely need a roadmap or something like a Trello to know who is working on what :)

about DNS records, 
it comes frome @Someguy123 since dan announce about STEEM DNS
https://steemit.com/namecoin/@dantheman/dns-via-steem
he did use json metadata 
https://steemit.com/steemit/@someguy123/steem-dns-your-username-dot-steem-dns-on-the-blockchain

but that's not mandatory

**Comment by Undeadlol1** [comment]
I am front-end developer of russian steemit project (we are called 'golos').
I have already done 90% of the work on i18n and more.
Currently i am working on
- i18n of strings, plurals, numbers and currencies
- i18n abstraction through api in case if i18n library replacement
- implementation of config file which will help you change things like APP_NAME and CURRENCY_SIGN in entire project
- bunch of over things.
In next few days i will be working on internationalisation of currencies through currency rates APIi's. Russian users should see their rewards in equivalent of russian rubles and lads from Great Britain should see money numbers in sterling pounds. (dunno if i will be able to implement this fully, but i will do my best)

You can check my progress at [our 'develop' branch](https://github.com/GolosChain/golos.io/tree/develop) of our project. I documented everything in app/locales/README.md and in app/Translator.jsx. If you want to see application translated to russian, you should go to Translator.jsx and change this
```
// to ensure dynamic language change, "key" property with same "locale" info must be added
return 	<IntlProvider locale={languageWithoutRegionCode} key={languageWithoutRegionCode} messages={messages}>
```
to this
```
return 	<IntlProvider locale={'ru'} key={'ru'} messages={messages}>
```
 @f3rnando you should really check my repo, so you will not have to recreate the will.

Btw i am having a little bit of a trouble implementing international tags and topics, because https://steemit.com/trending/конский just doesn't want to work for me. If you have any input or know anyone who i can talk to, it would be great.

**Comment by f3rnando** [comment]
@Undeadlol1 I was aware of golos :) I will defintely check that implementation. Your <IntlProvider like clearly shows that you are in the same path I am. 

@mynameiskeo, @skzap  lets start a steem.chat i18n-effort channel. To begin with. :)

I'm happy to hear from you all. Thanks.

**Comment by f3rnando** [comment]
I just created an organization to keep it clean. 
Added you guys as members with full access.
https://github.com/steemit-intl

**Comment by f3rnando** [comment]
@valzav @jcalfee @roadscape @mynameiskeo @skzap  we were discussing in steemit.chat (steemit-i18n-dev channel) a few points to get this done:

9. Should we wrap strings before PR or would it be better to PR just the i18n support files? If we take the task to wrap all strings, it could get to be a merge nightmare for you (steemit devs)
10. What naming should be choosen? I personally like __(), others prefer translate(), none or a few t().
11. given #2 what about html and plurals translate? (eg: __p() __HTML, translateHTML(), etc)
@Undeadlol1 is already using translate(), I believe that this might be the logic way to go.
12. Should I rebase previous to PR? or merge? or pull --rebase? Please indicate the best approach.

3. Update: Finally, **babel-plugin-react-intl** wasnt used.

Thanks in advance.

**Comment by valzav** [comment]
1. Let's start with i18n support files, we can add translations later.
2. I would prefer t() or translate()

@f3rnando as I understand your solution is separate from @Undeadlol1 so they have nothing in common?

**Comment by f3rnando** [comment]
@valzav
It is derived from @Undeadlol1's code, with a few tiny changes here and there.. 
Notice that Golos changed a few things since then, so It might look a bit different now. Sadly I had to leave out a lot of code from Golos, as it is substantially diverging, my concern was to make a branch that is easy to merge.

It's not really a lot of code, you might refactor it all by yourself, I believe that you will find useful mostly the lang files.

**Comment by valzav** [comment]
Let's continue to work on i18n support in 233-i18n branch.

**Comment by valzav** [comment]
I'm going to merge branch 233-i18n into develop today

**Comment by roadscape** [comment]
Cross-posting from https://github.com/steemit/steemit.com/pull/430:

---

IMO, translations need namespacing otherwise they will get out of control.. here's examples of what I consider developer/translator-friendly structure:

https://github.com/plataformatec/devise/blob/master/config/locales/en.yml
https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/en.yml

It would be better to do this sooner than later

**Comment by sneak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [internationalization](https://trello.com/c/sCp0CziU/56-internationalization)

**Comment by TimCliff** [comment]
Sorry for the 'stupid question', but can someone please explain what this new feature will do? I can tell it has something to do with language transition, but how will it actually impact what users can do on the site?

**Comment by sneak** [comment]
This allows the site to present the site UI in multiple languages, depending on the language setting of the browser accessing.

i18n = an i, followed by 18 letters, followed by n = internationalization

**Comment by valzav** [comment]
There are a lot of `Invariant Violation: [React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.` errors.
I need your help with loading Intl polyfill.

**Comment by Undeadlol1** [comment]
https://github.com/GolosChain/tulupchik/blob/master/server/server-html.jsx#L28
https://github.com/GolosChain/tulupchik/blob/master/app/locales/README.md#how-to-add-your-own-language

**Comment by relativityboy** [comment]
@valzav @originated - should this issue be closed?
