### ISSUE TITLE
Decide what to do with Facebook and Reddit OAuth.

### ISSUE THREAD

**Issue by gl2748** [steemit/condenser#2389]
We have some code for delegated user authentication through Facebook  and Reddit.
https://github.com/steemit/condenser/blob/master/src/server/api/oauth.js

It is not clear if this is still needed.

### Do we still use this code.

- [ ] yes.
- [x] no.

### Do we want to keep this code.

- [ ] yes.
- [x] no.

### Do we want to replace use of `purest` lib with `request-promise` per: https://lorenstewart.me/2017/03/12/using-node-js-to-interact-with-facebooks-graph-api/
 - [ ] yes.
 - [x] no.

**Comment by jayserdny** [comment]
My opinions:

- **Is this code used?** I believe it is not used due to I don't see any auth through Facebook nor Reddit in the frontend. Thus, I believe this code is not longer used.
- **Need to keep this code?** Based on my response above, I believe this code is not needed anymore
- **Replace purest with request-promise?** request-promise is better maintained than purest, all the dependencies are up to date, and there is not vulnerabilities (yet) in this lib.

**Comment by valzav** [comment]
I'm working on removing oauth all together

**Comment by bnchdrff** [comment]
fixed in https://github.com/steemit/condenser/pull/2426
