### ISSUE TITLE
Pressing enter in "Title" or "Tags" field destroys text. iOS browsers.

### ISSUE THREAD

**Issue by xanoxt** [steemit/condenser#272]
Hi. I'd like to report an issue with the editor, it is local to iOS browsers (tested it in Chrome & Firefox), and confirmed, that on non mobile it works both in Chrome and Firefox correctly.

Issue: When you press 'return' in the Title or tags field, it either clears all of the text in "Write your story..." field, or posts it to the blockchain. That depends if there are tags/tags present, or not.

Expected behaviour: The editor should ignore the 'return' button, and only post when you click on thr 'Post' icon. It should not clear the text field.

Steps to reproduce:
iOS version 9.3.4 latest Chrome & Firefox browsers
1. Enter sample text into "Write your story..." field.
2. Go to "Title" or "tags" field.
3. Press 'return' on the virtual keyboard.
   ...
4. Profit! Or rather in this case loss. The field is now empty, and the text is gone, even if you reopen it in the new tab!
5. If both title and tags present, the story is commited to the blockchain instead!

I hope this is fixed sometime soon. Most likely the error is something trivial in those two fields.

**Comment by theghost1980** [comment]
I have tested this issue, even that is a very old one. (_I would say it's being fixed since that time_)

Tested on Android Mobile phone (Android 5.1 ):
Screen Shots Results:
1. Pressing "ENTER" (_Return key_), after positioning the cursor inside of TITLE Box:
![screenshot_2017-03-29-16-31-42](https://cloud.githubusercontent.com/assets/24734575/24476071/0c14e6f6-14a0-11e7-8f81-85ad45b1b14b.png)

2. Pressing ENTER (_Return key_), after positioning the cursor over TAGS box:
![screenshot_2017-03-29-16-32-14](https://cloud.githubusercontent.com/assets/24734575/24476118/2eca1bee-14a0-11e7-9d33-8a5b69222417.png)

Tested on MacOS (MacBook Pro under Sierra 10.12.3 ):
1. Positioning the cursor over Title Box, then, hitting ENTER key (On physical keyboard and also, using the keyboard viewer)
<img width="709" alt="screen shot 2017-03-29 at 16 36 02" src="https://cloud.githubusercontent.com/assets/24734575/24476226/8943b2c4-14a0-11e7-93d3-006fabf4a35c.png">

<img width="527" alt="screen shot 2017-03-29 at 16 38 32" src="https://cloud.githubusercontent.com/assets/24734575/24476227/8984e438-14a0-11e7-8ca7-06ca9d6e0f25.png">

<img width="835" alt="screen shot 2017-03-29 at 16 38 44" src="https://cloud.githubusercontent.com/assets/24734575/24476228/89a89ed2-14a0-11e7-91ef-b6a5c7c86e43.png">

2. Positioning cursor over TAGS box, then pressing ENTER key:
<img width="702" alt="screen shot 2017-03-29 at 16 35 47" src="https://cloud.githubusercontent.com/assets/24734575/24476288/baa29f88-14a0-11e7-9562-7eb4eaab7579.png">

As you can see, looks like this issue has been solved, I would say that if under MacOs is working well, under IOS it should as well (But so far it hasn't being tested on iPhone).
I hope it helps!

**Comment by mcifani** [comment]
Thanks @xanoxt for testing.  Working as described here, closing.
