### ISSUE TITLE
Bring back SBD to steem converter

### ISSUE THREAD

**Issue by ajayyy** [steemit/condenser#2910]
SBD price has gone back down to 1$

**Comment by TimCliff** [comment]
I think it was removed more because it was seen as more of an “advanced user” feature. For the “average user” it is much simpler to just trade SBD for STEEM on the internal market. For advanced users who have a use for the conversions feature, there are other options (such as SteemConnect).

**Comment by ajayyy** [comment]
Won't removing it make the peg not as successful as people will not be
getting 1 dollar worth of steem?

**Comment by TimCliff** [comment]
If the peg is working, they should be able to buy a dollar worth of STEEM on the internal market.

**Comment by ajayyy** [comment]
But that is how the peg is made

**Comment by TimCliff** [comment]
The blockchain allows users to convert 1 SBD token into "approximately one USD worth of STEEM" (based on the 3.5 median price feed from the witnesses). The price of SBD is determined by traders (buying and selling), and the supply/demand of SBD. It is not necessary for condenser to expose the conversion function in order for the "peg" to work properly. As long as there is a way for the "advanced users" who deal with conversions to buy SBD from an exchange or the internal market and convert, then there will be support for the price of SBD.

The conversion feature adds a lot of confusion for the "average user" because mostly what people want when they convert is just to have their dollar worth of STEEM. It is much simpler for these users to just trade for STEEM on the internal market, because then they do not need to wait 3.5 days, and in a lot of cases the conversion results in less than a dollar worth of STEEM due to STEEM price fluctuations - which is bad for the user experience.

**Comment by ravau** [comment]
Hi, I think that internal trade is not enough when we have situation on the market like this occuring now:

sbd < 1
steem < 1

For example ratio steem/sbd for now is **0.89** on internal market

But we assume that sbd should be 1$, so the ratio should be more like **0.85** now. Because of that sbd 1$ peg doesn't work. If there was option to convert sbd to steem we would have people driven by arbitrage option, and SBD eventually will go faster to 1$.

However me make the inappriopriate assumption that everyone knows that sbd should be 1$. Why? We need mechanisms not a faith :)

**Comment by fractalnode** [comment]
maybe it could be solved in this way

<pseudo code>

if  (1 SBD < 1 USD )  {
     convert ( 24h period like bitUSD )
} else if ( 1 SBD > 1 USD ) {
     convert disabled & SELL SBD for STEEM at market price instantly
}

**Comment by roadscape** [comment]
Going to close this issue as the wallet has moved to https://github.com/steemit/wallet
