### ISSUE TITLE
Logged in users shouldn't get: "Join... Sign up.Get STEEM!" message

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/condenser#2999]
Use case:
I'm logged in user with my posting key or password, I'm trying to perform some action that requires active key, I get such screen:
![loginreturning](https://user-images.githubusercontent.com/6341057/44900828-f1532580-ad05-11e8-9e2b-e3e2a93ac245.png)
The bottom part is not needed here (i.e. for users that are already logged in)

**Comment by quochuy** [comment]
@roadscape @Gandalf-the-Grey 
I guess this should be moved to the wallet repo?

**Comment by roadscape** [comment]
Yes, it's now a wallet issue, however on that side we should remove the Join/SignUp message altogether since it's not meant for guest browsing.

**Comment by quochuy** [comment]
@roadscape
hmmm, however, unless I've missed something, there should not be any actions on the Condenser that requires you to use your active/owner key hence the login screen should not show again if you are already logged in. As for logged out users, it should still be OK to display the join/signup message. Is that correct?

**Comment by roadscape** [comment]
@quochuy correct.

**Comment by quochuy** [comment]
@roadscape 
Then we don't need this work anymore on the Condenser, because:
- we still need the Join/Sign-up message for anonymous users clicking on the Login link, as if they don't have an account the button will redirect them to the Wallet site.
- the login link won't appear for signed-in users
- the condenser does not have any actions requiring login in with another private key, so nothing should trigger the login screen

**Comment by roadscape** [comment]
Well put. Closing, thanks!
