### ISSUE TITLE
My own comments shouldn't be hidden

### ISSUE THREAD

**Issue by Smittyvb** [steemit/condenser#3005]
If a certain user is logged in, their own comments should never be greyed out/hidden.

**Comment by pkattera** [comment]
Hi @Smittyvb – Is this for the situation where the logged user has one of their own comments hidden due to low ratings?

In this case, I agree that the user should be able to see their own comment without it being hidden. However, they should be made aware that their comment is not being displayed to other users. 

How about we introduce a new label that says something like 'hidden due to low ratings' above their post and then display their post normally? That way, their comment isn't hidden but they're aware about the downvote activity?
