### ISSUE TITLE
Replacing Trending page with Promoted page

### ISSUE THREAD

**Issue by mahdiyari** [steemit/condenser#3120]
We can try and use the built-in ability of steem blockchain to burn more tokens and increase the price of STEEM and SBD
Now, some of the crypto projects are using steemit.com to promote their projects and they are using bid bots!
Why not using the Promoted page instead of the Trending page?
Promoting a post will burn SBD, and burning SBD could help exit from this sbd/steem 10% peg situation (printing STEEM instead of SBD). As a result, the SBD price will return to the 1 USD and printing more STEEM instead of SBD will be paused and this can increase the price of STEEM in the longer term.

Also, changing the Trending page to the Promoted page is not a hard job. It requires a few minutes of coding.

STEEM is going deep and deeper, we need to take an action and release a good work.
My proposal: remove trending page from steemit.com's homepage and replace that with the promoted page.
I think just high-quality posts will be there because people don't want to spend money to promote a low-quality post.

**Comment by Smittyvb** [comment]
See #1072/#2908, another option is to intersperse promoted posts into the trending page.

**Comment by propertunist** [comment]
as poor as the trending page has become due to bid bots, replacing it with the promoted page would do even more damage to 'proof of brain'. steem is fundamentally designed to use proof of brain as a primary function and the trending system is the main way of displaying the results. tackling bid bots requires them to specifically be targeted in some way, such as the 'voter muting' feature i designed some time ago that empowers each user to elect to remove the effect of votes from any specific account when they view the trending/hot and other pages. i have seen this tested now and it works very effectively to produce real trending lists that represent the kind of quality that i understand the community to produce and that is likely to be valuable to information consumers.

**Comment by mahdiyari** [comment]
We can keep trending page and remove bot upvotes, but not as a home page of steemit.com
The point here is STEEM/SBD price!
Also, filtering content and authors or votes is against decentralization of the blockchain

**Comment by propertunist** [comment]
you appear to have been promoting the idea of replacing the trending page with the promoted page - meaning that the promoted page would become the homepage of steemit.com. however, proof of brain is the key selling point of steem and that is why people look (looked) at the trending page and not the promoted page. people don't want to see the promoted page, in general (Which is why it would make more sense to put promoted posts inline with trending posts (as google does with google ads).

new users would see the promoted posts on steemit.com and be put off by their low quality nature and more experienced users would just not look at it and would go to the trending page anyway. i think you will find if you ask them that most project owners who pay for bid bots do it partially because they make a profit. you are asking them to not only stopping making that profit, but to also take on a big cost. or am i missing something in your proposal?

allowing users to filter content based on their own personal choices is in no way against decentralisation and actually is pro-decentralisation in that every person gets to choose their content instead of having it chosen entirely for them by an algorithm. people can run browser plugins to do this functionality anyway and it is all entirely voluntary with no-one being overpowered.

**Comment by Kiaazad** [comment]
giving more visibility to the promoted page does nothing to hurt the bid bots, the bid bots sell the vote amount, promote has a completely different use, people wouldn't spend money to promote a post if they don't believe in it.
if you ask me, the promoted post should be randomly pinned to the top of users feeds as well as the first page.

**Comment by gryter** [comment]
I don't think pinning posts should be used for anything other than critical announcements. 

If users start seeing random posts pinned to their feeds there will be increasing user dissatisfaction.

**Comment by roadscape** [comment]
Something like #2908 is preferred
