### ISSUE TITLE
Follow List not alphabetical

### ISSUE THREAD

**Issue by novacadian** [steemit/condenser#3160]
When accessing steemit.com, on January  11, 2019, the Following List is no longer in alphabetical order.

https://steemit.com/@novacadian/followed

**Comment by novacadian** [comment]
So when you are fumbling around in someone else's Following List are you looking who was the last accountil they started to follow or if they are following you?

Id the later then which is quicker to look yourself up, on the position you are on the time scale of follows or alphabetical. 

This is definitely a dev created bug.

**Comment by novacadian** [comment]
So when you are fumbling around in someone else's Following List are you looking who was the last account they started to follow or if they are following your account?

If the later then which woukd be a quicker look up?  Alphabetically or your position on their following time line?

This is definitely a dev created bug.

**Comment by roadscape** [comment]
I strongly suspect most people will find it more useful for the "Followers" and "Followed" pages to show newest relationships first. And an efficient way to check if someone is following you would be to add a "Follows You" indicator function on others profile pages. (This is what Twitter does)

Closing this for now since it's mostly a backend concern; there is more information here: https://github.com/steemit/hivemind/issues/167
