### ISSUE TITLE
Html parsing does not place line breaks correctly near images

### ISSUE THREAD

**Issue by drov0** [steemit/condenser#3210]
Hello, 

Code and images will be more easy for me to explain the bug : 

If I input the following code I get no line break after the image

```
<p>text</p>
<img src="https://i1.wp.com/thecreativecrypto.com/wp-content/uploads/2019/02/nfts-1.png?fit=640%2C291&amp;ssl=1" alt="" class="wp-image-6289"/>
<br/>
<p>text</p>
```

![image](https://user-images.githubusercontent.com/22356916/52855796-c711ea80-3122-11e9-9c5b-9be37686c5f7.png)

the expected output would be  : 

![image](https://user-images.githubusercontent.com/22356916/52855920-2d970880-3123-11e9-9142-8692a78f8f44.png)

Interestingly, if I put a second `<br/>` it then produces the expected output.

```
<p>text</p>
<img src="https://i1.wp.com/thecreativecrypto.com/wp-content/uploads/2019/02/nfts-1.png?fit=640%2C291&amp;ssl=1" alt="" class="wp-image-6289"/>
<br/><br/>
<p>text</p>
```

This is a weird corner case that only happens near images (or I may have missed it elsewhere).

**Comment by quochuy** [comment]
@roadscape
I don't think this is a bug. Images are set to inline-block so that a text that follows an image will be on the same line as the image (providing there is enough space in the container). Adding a <br/> will just go to a new line.

If <img> was `display: block` like <p> then a text that follows would already be on a new line so <br/> will add an empty line after the image. But using `display: block` will prevent the text from wrapping around the image if the image is smaller.

I think it's better to leave things as they are now and users can choose whether they like less pace or more space by adding a secondary <br/>

**Comment by drov0** [comment]
@quochuy you may need to edit your reply, github parsed all of those html tags so they don't appear

**Comment by roadscape** [comment]
Concur with @quochuy's assessment; also, if the `<img>` was wrapped in `<p>` then you should get all the expected breaks without needing any `<br>`.
