### ISSUE TITLE
Witness vote reminder

### ISSUE THREAD

**Issue by economicstudio** [steemit/condenser#3242]
![](https://cdn.steemitimages.com/DQmervQyig9mVVWpm12NXJt4WAxzPEVMvNcszuN7YSs6jDX/pie-SP.png)
> [Witness of the people, by the people, for the people](/@blockchainstudio/witness-of-the-people-by-the-people-for-the-people) The left pie chart shows the ratio of all (voted or not) SP. The inner pies show what percentage of SP in each category voted for witnesses, i.e., SP-weighted turnout in each category.

As shown in [Witness of the people, by the people, for the people](/@blockchainstudio/witness-of-the-people-by-the-people-for-the-people), many people do not do witness votes. Actually I've seen many people who do not know even the existence of witness votes. Also there were many people who thought that it can be done only once in some specific period.

**While not voting at all is also one way of voting, it's quite different if they actually don't know the existence or how to do.**

Steem is a blockchain with DPoS (Delegated Proof-of-Stake) consensus mechanism. The importance of the witnesses and witness voting cannot be overemphasized.

Thus, it'd be much better if there is a periodic reminder of witness votes. 

This can be a pop-up window such that users have to click something to proceed. The recent warning pop-up for non-posting key login is a good example.

![](https://files.steempeak.com/file/steempeak/blockchainstudio/NpKLPjWZ-Screen20Shot202019-03-1920at203.36.2520PM.png)
> Recently introduced warning pop-up for non-posting key login

In any sense, we shouldn't enforce users to do witness votes (since no voting is always one form of vote). However, at least users should be informed that there is witness votes.

![](https://cdn.steemitimages.com/DQmWdZqaAHG5dDhjmoLyaUP86tGrLicWTnh355xniEz9zCQ)

So for users who have never voted (nor set proxy), showing pop-up in the above  would be very informative and helpful.

**Comment by roadscape** [comment]
Good ideas. Implementation would need to be careful not to overwhelm new users. It's also a little more complicated now that the witness voting feature lives in a different app. We could also leverage a future notification system to deliver voting reminders to users instead of doing it up front. The witness voting page may be the best place to include a description of what witnesses are and the role they play. If this is something you'd like to address feel free to submit a PR to the wallet repo: https://github.com/steemit/wallet
