### ISSUE TITLE
Unable to click the resteem button

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#3346]
Due to the icon positioning, the resteem button is not clickable here:
![image](https://user-images.githubusercontent.com/20735105/57897914-8195b400-781c-11e9-98cf-d26163a8e74d.png)

I'm using Chrome browser. Let me know if there are any other details needed to reproduce.

**Comment by roadscape** [comment]
Thanks for the report. I am able to reproduce. Most likely this was due to the addition of the downvote button.

**Comment by economicstudio** [comment]
I believe eventually the relevant code should be rewritten completely. Due to many criticisms of the location of downvote, I tried to move it somewhere when it was initially introduced, but since it is used in three (blog, post, reply) different situations, it was very hard to make all of them show properly. Also zoom matters. I actually spent a few hours at that time, but I'm not an expert of style sheet, so I gave up.

**Comment by quochuy** [comment]
@roadscape increasing the max-width of the CSS class .PostFull from 50rem to 54rem does not increase the width of the post body but enlarge its parent container enough to allow proper display of both the Resteem button and the author + author tag (`Steemit Team`).

Not sure if there are any impacts of increasing that max-width but here are the results:

Before
![Screen Shot 2019-05-22 at 8 10 26 am](https://user-images.githubusercontent.com/310654/58134196-5f12f900-7c69-11e9-815e-56c39fd2027a.jpg)

After
![Screen Shot 2019-05-22 at 8 10 34 am](https://user-images.githubusercontent.com/310654/58134203-64704380-7c69-11e9-9e43-df77c13c31d6.jpg)
