### ISSUE TITLE
Proposal: canonical links and json_metadata

### ISSUE THREAD

**Issue by aaroncox** [steemit/condenser#336]
If you'd rather I take this to steemit.com for a discussion, I'm more than happy to start up a post. I figured a simple agreement here though may be easy enough. 

I'm proposing a simple change to the way that steemit.com generates it's canonical links, to establish a standard use case of SEO for non-steemit.com websites that are powered by the steem blockchain. The change within this codebase would be simple:

> By default on each comment, steemit.com generates the canonical link meta tag as normal. However, if within the `json_metadata` field the `canonical` property is set, it will use that value in place of the steemit.com domain.

This would become a best practice for anyone developing a website displaying user generated content from the steem blockchain.

For example, I created a post in with the tag #steemws, titled `steem.ws - The public steem api cluster`. By default, when viewing the post on steemit.com, the canonical link included into the content would be:

`https://steemit.com/steemws/@jesta/steem-ws-the-public-steem-api-cluster`

However, if when this post was created, I set the `canonical` field within `json_metadata` to `http://jesta.us`, when viewing the post on steemit.com the canonical link would now be:

`http://jesta.us/steemws/@jesta/steem-ws-the-public-steem-api-cluster`

This will let content creators specify the origin of their content and control a bit of it's SEO. Bots  could also use this to avoid accidentally flagging original content as plagiarism. This concept could also be further expanded to other SEO criteria, but I feel the canonical link is the most important of the bunch, especially with this content technically being available for any website. 

I am not asking for steemit.com to allow for the addition or modification of this data, and by default, all canonical links should default to steemit.com. However, if using an external tool (such as a CMS build on steem for running a custom website) I'd expect the tool to automatically append this data to any posts created from that website. 

Is this a reasonable request? If so, I'll put forth the effort and issue a pull request.

**Comment by adcpm** [comment]
This proposal is totaly legit. I don't see a better way to handle the case. We have to give the article author the SEO value of his article. Without this i see a lot of duplicate content issues...

**Comment by valzav** [comment]
I support this idea. Also I think we need to allow users to provide canonical link on steemit.com as well, e.g. we can add "Not original content" checkbox, when checked it will add additional input called "Original URL" and this url will be used as canonical.

**Comment by roadscape** [comment]
@aaroncox we support such a way of handling canonical URLs.

> However, if when this post was created, I set the canonical field within json_metadata to http://jesta.us, when viewing the post on steemit.com the canonical link would now be:

I would recommend always using the full URL within this field as opposed to setting just the domain.

**Comment by aaroncox** [comment]
Apologies for missing the updates on this, excited to see it implemented! 

You're absolutely right it should be a full URL to the page directly. I'll be implementing this throughout my projects during my next cycle of updates, as well as defaulting all non-specified metadata back to steemit.com.

A future idea could be to a fallback that automatically generates this data based off of the `app` meta tag that has become a standard across many platforms. For example, just knowing:

```
{
  "author": "jesta",
  "permlink": "test-post",
  "category": "test",
  "json_metadata": {
    "app": "busy/0.1"
  }
}
```

We could generate the canonical link to be `https://app.busy.org/test/@jesta/test-post` within each of the platforms. If the user specified a `canonical` field it would override this, but would provide a nice cascade of fallbacks when it's not specified:

`json_metadata.canonical` > `json_metadata.app` > default to `https://steemit.com`

**Comment by aaroncox** [comment]
I'm going to be spending some time in the next month or so digging into linking preferences on chainBB and will likely take a stab at some of this SEO/Canonical logic as well. Referenced above is my issue for tracking and I'll report back once progress is made.

**Comment by plink01001** [comment]
Are there plans to make any additional changes for this issue, or should it be closed?

**Comment by aaroncox** [comment]
I'll close this since it's just an old discussion thread at this point. The issue itself of canonical linking (and json_metadata usage at large within the Steem ecosystem) is still important and needs a solution - but it's more than just a condenser topic.

**Comment by roadscape** [comment]
https://steemit.com/steemdev/@howo/steem-improvement-proposal-canonical-links

**Comment by relativityboy** [comment]
The following was taken/modified from - `https://steemit.com/steemdev/@valuproposition/re-jesta-re-howo-steem-improvement-proposal-canonical-links-20180217t054225178z`

I like the utility of the `canonical` property.

I'd suggest we start with both a `canonical` and an `app_account` (that is an account associated with _only_ the app that assisted in creating the post). 

At some point in the future we can either:
1. agree on a kind of "meta schema" that will allow the account `app_account` to publish a configuration set for in a special tx; so that all clients can generate the correct urls by pulling the most recent tx for that app_account.
1. the app_account could publish special tx with a javscript function in the body that would take a post and transform it into the correct canonical url. (this is a terrible idea for all the obvious reasons) 
1. have a standard js lib in an npm style repo somewhere that everyone has access to, with the functions describe in #2, but vetted by the publisher (this is terrible for a mostly different set of reasons)

If we get sufficient community support, and add in the concept of trusted app_accounts (with some additional complexity) any of the above would get the job done 'well enough'.

This really does need to happen. For all our sakes.

**Comment by bonustrack** [comment]
On busy we are using this listing of apps: https://github.com/busyorg/steemscript/blob/master/apps.json to get apps info. 3p app owner doing PR from time to time to add their app. We are adding the repo like this: https://github.com/busyorg/busy/blob/master/package.json#L103 so it get constantly updated.

**Comment by RenaudGagne** [comment]
So why the "meh" response from Steemit? **This has been an issue for 2 YEARS.** The best example is with SteemPress...thousands of website are now using the steem blockchain but their website might be damaged because you haven't implemented this change yet. It doesn't only hurt them, it also hurt steemit.com SEO.

**Comment by drov0** [comment]
A good first step to avoid abuse on the "steemit.com" domain while helping the seo of the other platforms would be to remove the self referencing caonical link when the app tag in the json_metadata is set to something else than "steemit"

**Comment by Smittyvb** [comment]
This will be resolved by PR #2947.

**Comment by roadscape** [comment]
@Smittyvb I suspect that it would be easier for such a standard to be widely supported if UIs just add a `canonical_url` to each top-level post. Otherwise `n` UIs have to maintain a set of `n` rules. The benefit of the `apps.json` approach is that it's retroactive. Steemit.com does not set this field currently, nor does busy.org afaict.

**Comment by Smittyvb** [comment]
@roadscape

Using `apps.json` allows UIs to change their URL scheme at will. They can also change domains. (For example, alpha.example.com to example.com.) Also, if an app shuts down, then it can be removed from `apps.json`, and Steemit will stop pointing to it.
Also, UIs won’t all need to maintain their own mappings. They can also use steemscript.
