### ISSUE TITLE
Steemimages shows old images

### ISSUE THREAD

**Issue by krischik** [steemit/condenser#3392]
A while ago I have added and resized a few images from steemitboard. Since then I have "leveled up"

Now a few month I have added the same pictures to a new document and instead currendly active pictures the pictures from the time I have added still shown.

It seems that steemimages is caching the pictures and never updates the cache.

Posting where the problem occours: 

https://steemit.com/utopian-io/@krischik/using-steem-api-with-ruby-part-12

**Comment by roadscape** [comment]
This is the archiving feature of steemitimages; the problem is that many original images are taken down, so forcing images to update can result in a wide loss. There is no trivial solution. For interfaces which rely on steemitimages hosting, the best approach would be to modify the URLs going forward, even if by adding a simple query string.

**Comment by krischik** [comment]
I this case the image isn't taken down but provided provided dynamically. So it's still there just differently.

I only rely on hosting. I only rely on resizing.

**Comment by roadscape** [comment]
@krischik it's a tradeoff; users are confused when old posts don't have images as well. But more users would be negatively impacted by removed images than by non-updating images.
