### ISSUE TITLE
Increase Tag Limit

### ISSUE THREAD

**Issue by thecryptodrive** [steemit/condenser#3446]
Currently Condenser supports 5 tags, with the advent of Tribes with other frontends requiring unique tags perhaps it's time to allow more tags per post. Maybe increase to 10 for now.

**Comment by wehmoen** [comment]
I suggest to not increase the tag limit but not to count tribe tags.
so you can have : `palnet tag1 tag2 tag3 tag4 tag5` but not `lol tag1 tag2 tag3 tag4 tag5`

New tribes could then send a pull request to the condenser repo to add their tribe tag to the list

**Comment by thecryptodrive** [comment]
That sounds fine too

**Comment by gryter** [comment]
Adding new tribes to tribe-tags via PRs seems resource intensive on developer time and tribe-owner time. Increasing limit in condenser is far simpler.

**Comment by economicstudio** [comment]
I implemented this to Nitrous https://github.com/steem-engine-exchange/nitrous/pull/57 which is merged and live, let me know if you want this on condenser too. I'm seeing that probably due to HF21, community PRs haven't been merged actively these days. https://github.com/steemit/condenser/pull/3310 is also still pending. I don't wanna waste my time if it's not considered seriously.

**Comment by thecryptodrive** [comment]
@economicstudio would be good to have on condenser too but good to know it is available on Nitrous. I can't say whether you would be wasting your time as I am not affiliated with Steemit Inc. Issue #3310 is very useful as well, VP and SP % bars would also be good for Nitrous and for Condensor, have a look at the bars on a TokenBB forum https://forum.bitsports.io for example. 

![image](https://user-images.githubusercontent.com/22358264/62100021-18362500-b2e4-11e9-99a8-f7255aae4412.png)
