### ISSUE TITLE
refactor bridge-api with sagas

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#3524]
Evaluate state transitions in `bridge-api` that should rely on sagas to modify state.global instead of relying on component state.

- [x] src/app/components/elements/SettingsEditButtonContainer.jsx https://github.com/steemit/condenser/commit/9965086e3f7fdfe2d57f723e7737f095b0caec32
- [x] src/app/components/elements/UserTitleEditButtonContainer.jsx https://github.com/steemit/condenser/pull/3540/commits/f66cd2ba0c6152c9e7e5bf3d21992203cef5e923
- [x] un/pinPost, un/mutePost
- [x] subscriptions

**Comment by JonathanPorta** [comment]
I originally thought this issue was a race condition between the API updating and the subsequent fetch.  (read before write) Therefore, I tried to add a timeout, in order to verify that the API had time to update, but the UI still didn't update. However, it seems that the API is returning the new value with the `getCommunity` call.

![image](https://user-images.githubusercontent.com/1451007/65595762-a7f9f780-df52-11e9-814a-7e3299ad27e6.png)

![image](https://user-images.githubusercontent.com/1451007/65594979-00c89080-df51-11e9-970f-66f353d985a0.png)

I am thinking the issue is that the `getCommunity` saga isn't dispatching the correct action therefore redux doesn't know to trigger component with a prop change.
