### ISSUE TITLE
comm leadership display

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#3666]
- hide owner acct on community home
 - on comm explorer, list the admins of each community

**Comment by gl2748** [comment]
@roadscape, i'm presuming by 'comm explorer' you mean the list of communities at: `http://localhost:8080/communities` it looks like in order to get the 'team' for each community, will involve adding the 'team' column to the `list_communites` endpoint ... 

https://github.com/steemit/hivemind/blob/55f5b2f777dbba6c277a668cc3f09b2aa0204cb0/hive/server/hive_api/community.py#L97

The alternative is to make a `get_community` call for each community returned by the `list_communities` call...

**Comment by roadscape** [comment]
communities returned by 'list_communities' now includes an 'admins' key

**Comment by roadscape** [comment]
#3677 merged
