### ISSUE TITLE
votes show double

### ISSUE THREAD

**Issue by themarkymark-steem** [steemit/condenser#3688]
I've been noticing votes showing twice on the beta site

Example: 
https://i.imgur.com/NaeMCHQ.png

**Comment by roadscape** [comment]
Thanks for the report!

**Comment by gl2748** [comment]
Hi @themarkymark-steem  I've not been able to reproduce this, is there a specific set of actions to repeat in order to see the 'double' vote as the issue describes? Otherwise, do you have a reference post that I can look at? Finally are there circumstances in which the duplicate vote being displayed goes away?.

**Comment by themarkymark-steem** [comment]
I tried to find an example but when I go back it behaves normally.  It only seems to appear sometimes but does not persist past a refresh or navigation away.

**Comment by roadscape** [comment]
Please reopen this issue if the bug can be reproduced.
