### ISSUE TITLE
Cover image not updating on the wallet page

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/condenser#3744]
A user changed his cover image but it's not updating properly on the wallet page. It's showing an older cover he uploaded.

https://steemit.com/@goldstreet
https://steemitwallet.com/@goldstreet/transfers

**Comment by ety001** [comment]
https://github.com/steemit/steem/issues/3274

**Comment by ety001** [comment]
# How to set the `json_metadata` field empty.

You can go to [https://steemyy.com/steemjs/](https://steemyy.com/steemjs/) and use steemjs sdk to set your `json_metadata` field empty.

```
const username = 'your_account_name';
const active_key = 'your_active_key';

const tx = {
    operations: [
        [
            'account_update',
            {
                memo_key: "your_memo_public_key",
                json_metadata: "",
                account: username,
            }
        ]
    ],
    extensions: []
};

steem.broadcast.send(tx, {active: active_key}, (e,r) => {
    console.log(e, r);
});
```

**Comment by ety001** [comment]
Because of the bad design of `posting_json_metadata` field, currently the logic to display the profile is confusion.

There are two operations to update account profile now, `account_update` and `account_update2`.
Due to the `account_update` needs active key to sign, that means editing `json_metadata` needs active key.

After condenser abused active key to login, users cannot edit their profiles. So someone made a new design 
 `account_update2` that allows users to edit profiles by posting key. I don't think this design is good. That makes confusion.

The current logic of displaying profile is that read `posting_json_metadata` first, if failed, read `json_metadata`.
