### ISSUE TITLE
GUI wallet only shows a few hours of author rewards history

### ISSUE THREAD

**Issue by thecryptodrive** [steemit/condenser#375]
I am having a huge problem reconciling previous author rewards, the GUI wallet only goes back a few hours and I can't get to older author rewards. Steemd only goes back 5 pages now also.

This is really difficult for businesses and gamification projects on Steemit
![image](https://cloud.githubusercontent.com/assets/22358264/19016139/53f8ea78-8812-11e6-97e9-2dd0109d2cb9.png)

**Comment by faddat** [comment]
While I thumbs-up'd this, there's not *too* much that can be done.  They don't want to "choke" the API by returning all of the data you require at once, and hence the pagination.

What to do?  Steemjson, sir.  It's my blockchain-eater, database shitter.

**Comment by aaroncox** [comment]
While that's a great solution for @thecryptodrive, that doesn't solve the underlying problem on steemit.com. I think this relates to steemit/steem#146, and adding the ability to filter `get_account_history` by operation type. 

Then when users load the rewards page, it could make an independent call to retrieve the last X rewards for the account and possibly paginate it simply by passing `author_reward` as the virtual op type filter.

**Comment by thecryptodrive** [comment]
Roadscape just gave me full history on Steemd, so I will be sorted now. Thanks guys for your input, we do need some better wallet history on the GUI for other users however, otherwise prima facie it looks like censorship of earnings and doesn't look good, not everyone will realise it's performance issues.

**Comment by pfunks** [comment]
In regards to this issue, it's not just a few hours for everyone, some people's wallet history stretches back months. Is there some event that triggers a transaction display reset on an account's wallet page? It's something I've wondered for a while.

**Comment by thecryptodrive** [comment]
Yeah I know it's weird, not sure why this is for some but not others..

**Comment by aaroncox** [comment]
Hopefully this answers some of the questions you guys raised:

Right now the account pages most likely use the `get_account_history` API method, which returns a set number of "history" items including votes, transfers, rewards, power ups, etc. Almost all types of activities are a part of this history. These items all come back together in chronological order.

So if the account page calls this method, and says "give me 500" results, it's going to be a combination of all activity up to 500 records in the past. In a simple example, the response on one account might be 495 votes and 5 rewards, while on another account might be 50 rewards and 450 votes. On that first account the reward page would only show 5 results, but that second account would go back 50 results. 

Until we get a more precise tool to use to lookup account history, we're going to have some oddities like this. That's why I referenced the issue above as a potential solution from the steem repository. This isn't just a limitation of steemit.com, but of steem itself.

**Comment by thecryptodrive** [comment]
Awesome, thanks so much for the information, that was a nice and easy to understand brief of what is happening. Hope there will be a fix later.

**Comment by sneak** [comment]
@faddat we need to build or use something like this in the future for steemit.com, no doubt. can we speak soon about your solution?

**Comment by thecryptodrive** [comment]
Go @faddat !!! Hope you will speak with @sneak

**Comment by faddat** [comment]
Of course-- always happy to speak with any member of the steem community
:).  faddat@gmail.com on google hangouts is best, I'll be around for the
next six hours or so.

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by roadscape** [comment]
@aaroncox nailed it; https://github.com/steemit/steem/issues/521 is a potential short-term workaround for this issue.

**Comment by roadscape** [comment]
Resolved; backend returns more history now
