### ISSUE TITLE
steemit.com down?

### ISSUE THREAD

**Issue by steemchiller** [steemit/condenser#3763]
The site seems to be down again.
Returns "500 Internal Server Error" for hours already.

**Comment by ayogom** [comment]
Steemit is currently under attack by DDos

**Comment by steemchiller** [comment]
Thanks for the info! It works stable again.
I hope they will finally find peace on their new chain...

**Comment by netuoso** [comment]
Come on don't spread BS. The Steem blockchain is over 60 minutes behind the Hive blockchain due to missed blocks and inefficiencies on the Steem network. SteemIt is having failures with deploying constant censoring changes and breaking their APIs. There was also a misconfigured blacklist that caused issues on sites.

There is no DDoS.

SteemIt just has incompetent devs and cannot patch their issues fast enough.
