### ISSUE TITLE
Missing sort orders for comments and the need for a total payout sort order

### ISSUE THREAD

**Issue by arhag** [steemit/condenser#62]
Certain sort orders available on the home page for top-level posts are not available for sorting comments within discussions. Specifically, sorting by popular and responses would be useful for comments.

I also think it is valuable to have another sort order for both top-level posts and for comments: payout. This would be the total SD value of past payouts together with the pending payout. I think that a discussion that is not archived (root post hasn't had second payout yet) should use trending as the default sort order as it does currently, but after the discussion is archived, it should switch to a defaulting to the payout sort order.

**Comment by TimCliff** [comment]
I noticed this, and considered it a "glitch". I don't know how the sort order on comments is supposed to work though. Maybe this is by design?

On [this post](https://steemit.com/voting/@timcliff/the-battle-of-upvote-weights-reviewing-the-arguments-with-extreme-use-cases), there is a comment "Good post, Where exactly is the slider...", which was a question that a user asked. There were a lot of replies to it, but nobody upvoted the comment.

Below that comment are a lot of other replies to the post, which do have upvotes. Example: "Finally a post that makes sense on...".

The comments with upvotes are appearing below the comment with no upvotes. To me this seems off.

**Comment by roadscape** [comment]
Semi-related request: highlight new posts since last read

**Comment by sneak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Better comment sort order (& highlight new posts)](https://trello.com/c/OEHHqJOp/58-better-comment-sort-order-highlight-new-posts)

**Comment by roadscape** [comment]
We have since implemented Payout sort order as the default.
